### ISSUE TITLE
KV Questions

### ISSUE THREAD

**Issue by cisaacson** [amenezes/discovery-client#29]
I have a couple of questions on the KV usage:

- If I want to list all keys, or do a find for keys that start with `t` how is the best way to do that?
- Do you have an example of how to implement a `watch` on a key? I want to trigger execution based on the change of a key

**Comment by amenezes** [comment]
Hi @cisaacson,

Soon I hope to update the lib documentation with more use cases. But for now:

To list all keys or find keys with some prefix can you use `recurse` and `keys` options in the `kv.read` method, for example:

```python
# considering the follow keys:
# key1: 1
# key2: 2 
# key3: 3

from discovery import Consul

c = Consul()
await c.kv.read('k', recurse=True, keys=True) # this will retrieve only keys

await c.kv.read('k', recurse=True) # this will retrieve keys and values
```
> to see all available options: https://developer.hashicorp.com/consul/api-docs/kv#read-key

I hope to include native support for watch functionality soon. But again, for now maybe you can use something like the following example:

```python
# considering:
# key: value
# test: 1234
import base64
from contextlib import suppress

from discovery import Consul

c = Consul()
value = '1234' # initial value


async def key_watch(key):
    while True:
        await asyncio.sleep(5)
        with suppress(Exception):
            res = await c.kv.read(key)
            current_value = base64.b64decode(res[0]['Value']).decode('utf-8')
            if current_value != value:
                print('Value changed')
                break
            print('Value not changed')
            

await key_watch('test')
# now change the value of 'test' key
```

In async environment can you use `create_task` rather than `await key_watch`, for example.

- https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task

**Comment by cisaacson** [comment]
Thanks for the quick reply, this gives us an idea of what to do.


--
Cory Isaacson
http://www.coryisaacson.com
